name: Expression & Contexts
on: [push, pull_request,issues, workflow_dispatch]

jobs:
  using-expression-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expression
        run: |
              echo ${{1}}
              echo ${{'This is a string'}}
              echo ${{ null }}
              echo ${{ true }}
              echo ${{ 1 > 2 }}
              echo ${{ 'string' == 'String'}}
              echo ${{ true && false }}
      - name: Dump Context
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'         