name: External Event
on:
    repository_dispatch: #should be in default branch, this supports activity types 
        types:
          - build
          - on-demand
     
jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.unit}}  
      
# To trigger workflow from postman
# https://api.github.com/repos/AbhishakeJain/github-actions/dispatches
# {
#     "event_type":"on-demand-test",
#     "client_payload":{ # client payload is to send additional data
#         "unit":false,
#         "integration":true}
# }