name: Manually Triggered
on:
    workflow_dispatch:
      inputs:
        string:
          description: A string input
          type: string
          required: true
          default: "Default Value"
        number:
          description: A number input
          type: number
          default: "01"
          required: true
        option:
          description: An option input
          type: choice
          default: "Option 3"
          options:
            - Option 1
            - Option 2
            - Option 3
            - Option 4
          required: true
        boolean:
          description: A boolean input
          type: boolean
          required: false  
        environment:
          description: "Environment"
          type: environment
          required: true
jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF  
      - run: |
          echo "String: ${{ inputs.string }}"
          echo "Number: ${{ inputs.number }}"
          echo "Option: ${{ inputs.option }}"
          echo "Boolean: ${{ inputs.boolean }}"
          echo "Environment: ${{ inputs.environment }}" 
# To trigger workflow from postman
#           https://api.github.com/repos/AbhishakeJain/github-actions/actions/workflows/manually-triggered.yaml/dispatches

#           {
#             "ref": "main",
#             "inputs":{
#                 "string": "from postman API",
#                 "environment": "production",
#                 "number": "17",
#                 "option": "Option 1"
#             }
#         }          

